### ISSUE TITLE
Tracking features versus informational data

### ISSUE THREAD

**Issue by ragrawal** [scikit-learn-contrib/sklearn-pandas#103]
Sometimes you want to apply some transformations to generate new columns but you don't want to use that as a feature while training your data. For instance if you have a timestamp and for debug purpose you convert it to date in %Y-%m-%d format. However you don't want to use it as a feature. Currently I have to maintain a list of columns separately that I would like to use as a feature. It will be nice if in the options for each transformer we can provide a tag indicating whether its a feature or informational element. 

Currently, my heck is to use alias field and whenever alias starts with 'predictor_', I use it as a feature for training the model. However a cleaner solution would be to have a boolean variable indicating whether the derived column is a feature or informational element. To make it more generic , we can have tags that takes a list of values and maintain a separate mapping between derived columns and tags. That way we can assign different tags to the same column and use it in different context.

**Comment by dukebody** [comment]
Hrm why don't you define two mappers, one you use to generate only the predictor variables, and another one to generate all features you want? Another option would be to have two separate mappers, one for the prediction features and another one for the informative ones, and merge the two output dataframes whenever you need it for a final result.

**Comment by ragrawal** [comment]
I agree that you can join them later on but I feel that way there is always some uncertainty as the join will be based on index. My biggest concern is what if the index has changed for reason. Hence I feel much more comfortable keeping my features and informational elements always together. I guess one great improvement will be to have a metadata dictionary that can be defined in the options and within the dataframe we keep mapping between transformed names and associated metadata dictionary. That way use can provide any context in this metadata dictionary.
