### ISSUE TITLE
Moving sklearn-pandas to scikit-learn-contrib

### ISSUE THREAD

**Issue by wesm** [scikit-learn-contrib/sklearn-pandas#114]
The pandas team has been discussing how to handle pandas add on projects, and one thing that came up is that this repo might be better located in scikit-learn-contrib

https://github.com/scikit-learn-contrib/

Separately, due to the way that resourcing works with Travis CI, we likely will create more GitHub organizations as a mechanism to expand our pool of CI workers.

Any opinions from the developers here? cc @jorisvandenbossche @jreback

**Comment by jreback** [comment]
could also move to pandas-contrib

either way is ok

**Comment by dukebody** [comment]
Hi @wesm and @jreback ! I personally don't mind too much as long as @arnau126 and I keep write access and the ability to add new people with commit access to the repo.

This project is using CircleCI right now, so it probably won't use up any Travis resources in the short term.

Thanks!

**Comment by jorisvandenbossche** [comment]
For this specific project, IMO it seems more appropriate to host it in scikit-learn-contrib (you should have write access there as well). But I am not sure about the process to get added there.

**Comment by jorisvandenbossche** [comment]
Information about requirements/workflow are here: https://github.com/scikit-learn-contrib/scikit-learn-contrib/blob/master/workflow.md

**Comment by dukebody** [comment]
@jorisvandenbossche, @wesm I asked for inclusion in https://github.com/scikit-learn-contrib/scikit-learn-contrib/issues/19.

**Comment by dukebody** [comment]
Done!

**Comment by jorisvandenbossche** [comment]
Great!
