### ISSUE TITLE
Failed to realize user defined transform through "FunctionTransformer"

### ISSUE THREAD

**Issue by DataTerminatorX** [scikit-learn-contrib/sklearn-pandas#122]
I want to define my own feature transformation, and then put it into `DataFrameMapper`. I tried `sklearn.preprocessing.FunctionTransformer` but failed. Can anyone help?

Say, now I have some data below
```
data = pd.DataFrame({ 'salary':   [90, 24, 44, 27, 32, 59, 36, 27]})
```

I found below code work well
```
feature_mapper = DataFrameMapper([
        ( ['salary'], FunctionTransformer(np.log1p) ) #  log transform
        ])
```
So I mimic it to realise a new transformation. First I define a `numpy ufunc`
```
def udf_divideTen(i):
    return i/10
divideTen = np.frompyfunc(udf_divideTen,1,1)
```
Then I put it into `DataFrameMapper`
```
feature_mapper = DataFrameMapper([
        ( ['salary'], FunctionTransformer(divideTen ,validate=False ) )
        ])
```

But when I use `feature_mapper.fit(df)`, it reported an error. 

Also, the approach of using `lambda` funtion [here](https://github.com/pandas-dev/sklearn-pandas/issues/60) , like
```
 feature_mapper = DataFrameMapper([
         ('salary', FunctionTransformer(lambda x:x/10 , validate=False))
    ])
 grid = GridSearchCV(pipe, cv=3,param_grid={'C':[0.5, 1, 2]}, n_jobs = 4, scoring ='accuracy' )
 grid.fit(Train, Trainy)
```
will cause another error `Can't pickle <function <lambda>` (but this error seems to be caused by `scikit-learn`)

**Comment by scotthuang1989** [comment]
can you post you whole code as whold py file?  I am not sure this line of code is right:

> ( ['salary'], FunctionTransformer(divideTen) ,validate=False ) 

the 3rd parameter of input tuple should be a dictionary, looks like a grammar error to me.

**Comment by dukebody** [comment]
> But when I use feature_mapper.fit(df), it reported an error.

Which error?
