### ISSUE TITLE
ImportError when import gen_features

### ISSUE THREAD

**Issue by pheman** [scikit-learn-contrib/sklearn-pandas#130]
Is there a significant API change for gen_features? I encounter the following ImportError when I import the gen_feature function.

>import sklearn_pandas as skpd
>print(skpd.__version__)
>from sklearn_pandas import gen_features

output:
1.5.0
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-58333222ffaf> in <module>()
      1 import sklearn_pandas as skpd
      2 print(skpd.__version__)
----> 3 from sklearn_pandas import gen_features

ImportError: cannot import name 'gen_features'

Thanks!

**Comment by devforfu** [comment]
@pheman I guess that `gen_features` is available only if you directly install the package from the `master` branch. Because this function was introduced recently, and doesn't exist in `v1.5`.

**Comment by dukebody** [comment]
Yep let's do a release. :)

**Comment by dukebody** [comment]
Released. You can download the last version from pypi.
