### ISSUE TITLE
fit_transform fails for multiple column transformation

### ISSUE THREAD

**Issue by thebeancounter** [scikit-learn-contrib/sklearn-pandas#131]
Hi 
I have multiple column names in the variable `other`
When i try to use the following code taken from [here](https://github.com/scikit-learn-contrib/sklearn-pandas):
`from sklearn.preprocessing import MinMaxScaler, LabelEncoder`
`mapper = DataFrameMapper([[other[0],other[1]],LabelEncoder()])`
`mapper.fit_transform(df.copy())`
I get the following error:

> raise ValueError("bad input shape {0}".format(shape))
> ValueError: ['EFW', 'BPD']: bad input shape (154, 2)

When I use the following code, it works great:
```
cols = [(other[i], LabelEncoder()) for i,col in enumerate(other)]
mapper = DataFrameMapper(cols)
mapper.fit_transform(df.copy())
```
To my understanding, both should work well and yield same results.
What am I doing wrong here?

**Comment by erikjandevries** [comment]
The `DataFrameMapper` takes a list of tuples (each tuple containing a column name and a transformer object). In your first code snippet you've given it a list, containing a list and the `LabelEncoder`.

You might want to have a look at the section  [Same transformer for the multiple columns](https://github.com/scikit-learn-contrib/sklearn-pandas#same-transformer-for-the-multiple-columns) which explains how to use the `gen_features` function.

**Comment by dukebody** [comment]
Yep, the issue with your first code snippet is exaclty what @erikjandevries points out. Please reopen if you think there is a bug.
