### ISSUE TITLE
Why TransformerPipeline?

### ISSUE THREAD

**Issue by amueller** [scikit-learn-contrib/sklearn-pandas#134]
Hey. Silly questions: it's not immediately obvious to me, but why do you need TransformerPipeline? Can't you just use sklearn.pipeline.Pipeline?

**Comment by dukebody** [comment]
Hi @amueller!

I didn't remember why we did this, I had to look it up. I guess the best explanation about why used a subclass is https://github.com/scikit-learn-contrib/sklearn-pandas/issues/46#issuecomment-162305604.

Do you happen to know if the original `sklearn.pipeline.Pipeline` has changed in a way we don't need the `TranformerPipeline` anymore?

**Comment by amueller** [comment]
Ah, that explanation makes a lot of sense, thanks :)
