### ISSUE TITLE
unicode handling error

### ISSUE THREAD

**Issue by DavideAllavena** [scikit-learn-contrib/sklearn-pandas#135]
Working with unicode text tokens i got this error using `DataFrameMapper` and `CountVectorizer`:
```UnicodeEncodeError: 'ascii' codec can't encode character u'\xe0' in position 7: ordinal not in range(128)```

To fix this I made this changes:
```
190c190
<             return t.values
---
>             return t.values.astype('U')
256c256
<                 return [name + '_' + str(o) for o in names]
---
>                 return [name + '_' + o.encode('utf-8').strip() for o in names]
```

**Comment by dukebody** [comment]
Which Python major version are you using, Python 2 or Python 3? I tried to solve this issue in the code, but cannot think of a good way that makes the code compatible with Python 2 and 3 at the same time and doesn't make assumptions about the encodings.

So I can only offer you a workaround:
1) If you are using Python 2, convert all your dataframe strings to bytestrings (encode them) before using the dataframe in a dataframe mapper. In Python 2 all quoted strings are bytestring by default, and `str` casts to bytestring.
2) If you are using Python 3, convert them to unicode. In Python 3 all quoted strings are unicode (text) by default, and `str` casts to text.

**Comment by dukebody** [comment]
Closing because I don't think there is any reliable and not tpp complex way of fixing this in both Python 2/3 at the same time and with both text and bitstrings as possible column labels.
