### ISSUE TITLE
In a pickle

### ISSUE THREAD

**Issue by woodmicha** [scikit-learn-contrib/sklearn-pandas#136]
I'm attempting to leverage `DataFrameMapper` in a `Pipeline` during fit step which works fine provided I train the estimator(s) every time I run the application.  Given the expense of training these regressions I've been caching trained models using pickle which has worked fine for pipelines, estimators of all types (classifications, ensemble models, etc) I've used. 

When using it with DataFrameMapper the estimator step loaded for the step in question (used to `LabelBinarizer`) had issues.  First the member variable built_features is None.  After hacking past that issue I encountered:

`sklearn.exceptions.NotFittedError: ['gear_id']: This LabelBinarizer instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.`

Not sure if this is an issue or an expected result.  I did see test cased related to pickle in your code base so I'm hoping it's expected to be able to do this.

One other wrinkle that may in fact be the root cause is I'm using `Pandas 0.19` instead of the latest in spite of the upgrade to the latest `DataFrameMapper` taking pandas to `0.21`.  I rolled pandas back due to my other models being pickled in the previous version not loading in the new version.  I think I can fix that through a data conversion using `pandas.HDFStore`.  I'll try next but wanted to first confirm pickled Mappers is an acceptable approach to preserving the transformation for use at the time of prediction.

Cheers and thanks for the great library!

Mike

**Comment by dukebody** [comment]
Hi @woodmicha !

Yes, for sure you can pickle the `DataFrameMapper` instances most times. We used pickled `DataFrameMapper`s in my previous work all the time for input data transformation.

From the description of you issue it seems like the state of the `LabelBinarizer` is somewhat not being saved correctly in, or restored correctly from the pickle. Would you mind submitting a small code snippet example that reproduces this error?

Regarding pandas 0.19, according to what is adverstised in the package info `sklearn-pandas` should be compatible with `pandas>=0.11.0`. If you find out that it doesn't work with `pandas==0.19` and it works with newer versions, please tell us so we can verify!

Also, pinging @arnau126 who works with pickled dataframe mappers all day and might be able to give you a hand here. ;)
