### ISSUE TITLE
Installing sklearn-pandas with Anaconda on Windows

### ISSUE THREAD

**Issue by pepaczz** [scikit-learn-contrib/sklearn-pandas#139]
Is there a way to get the `sklearn-pandas` package installed using `conda`  on Windows 10?

P.S. this is my first "issue" message in Git, hope I am at a right place.

**Comment by pepaczz** [comment]
Made it running using `pip` in a mean time.

**Comment by devforfu** [comment]
@pepaczz Do not know for sure if there is an "official" distribution of `sklearn-pandas` on `conda`, but you could search [here](https://anaconda.org/search?q=sklearn-pandas) next time for different conda channels that could have packages absent from the default one. That is what I [have found](https://anaconda.org/creditx/sklearn-pandas), for example:
```
conda install -c creditx sklearn-pandas 
```
But, the version could be outdated or required platform is missing (as in your case).

At the end of the day, it is always possible to clone repo and install package from sources like:
```
> git clone https://github.com/scikit-learn-contrib/sklearn-pandas sklearn_pandas
> cd sklearn_pandas
> pip install -e .
```
