### ISSUE TITLE
Feature request: option to manually specify replacement value used by CategoricalImputer

### ISSUE THREAD

**Issue by rwjmiller** [scikit-learn-contrib/sklearn-pandas#144]
The mode is a good replacement value to use most of the time, but it would occasionally be useful to be able to specify a different value, e.g. on the basis of domain knowledge.

Would it be a lot of work to add this functionality? My python code is not generally of such a standard that I would feel confident contributing to the project.

**Comment by dukebody** [comment]
It shouldn't be a lot of work! Thanks for implementing this.

**Comment by dukebody** [comment]
Fixed in #145.
