### ISSUE TITLE
simplifying interface

### ISSUE THREAD

**Issue by ragrawal** [scikit-learn-contrib/sklearn-pandas#147]
Hi,
I love sklearn-pandas and it has been extremely useful in helping setup transformation pipeline. However, there are few holes for which I have started a new project that creates another level of wrapper around sklearn-pandas. You can find my package over [here](https://github.com/ragrawal/pandas-transformer). It especially fix these two issues:

1. Simply interface to apply transformation on original or derived columns.
2. Wrap simple functions and transform them into a derived class of TransferMixin. 

I would love to integrate my project with sklearn-pandas itself. Let me know what you guys think about this. 
Ritesh

**Comment by devforfu** [comment]
@ragrawal That's a great idea to improve `sklearn-pandas` but could you please tell us more about the key differences with your project? As I can see from your examples, we can achieve the same goals with:
```python
from sklearn.preprocessing import FunctionTransformer as func_t
mapper = DataFrameMapper([
    (['AGE'], func_t(np.log1p), {'alias': 'age_log'}),
    (['AGE'], func_t(np.exp), {'alias': 'age_exp'}),
    (['RM'], [func_t(f) for f in (np.log1p, np.exp)], {'alias': 'derived_rm'})]
])
```
Also, that would be great to make sure that objects generated with the new interface are compatible with the old API and don't duplicate the existing hierarchy.

**Comment by ragrawal** [comment]
The main pain point for me was that often I have a feature that is broken down into multiple features. Eventually, I have to process one or more of these derived features. Existing API doesn't allow to work on derived features. The only solution is to have two separate DataFrameMapper. That was the primary motivation. 

Also (althoug minor), I like to express things as a function rather than passing an array. So I added an apply method that internally constructs an array.

**Comment by ragrawal** [comment]
The recommended approach make sense for simple transformations that are not too costly. Above, you are splitting the string into two parts twice: once in get_day and second time in get_amount. Assuming, if splitting a string is an expensive operation, ideally you want to do it only once. In that case the series of operations will look like this:

```
transformers = DataFrameMapper([
    ('dayAmount', get_day_amount, {'alias': ['day', amount']}),
    ('amount', MinMaxScaler(), {'alias': 'amount'})
    ('day', LabelEncoder())
])
```
I had a similar situation where the input feature was a raw json string and I had to extract many different things from the string. Converting each time the whole json string into json object is an expensive operation. In theory I could have done that outside the DataFrameMapper, but I feel it defeats the purpose
