### ISSUE TITLE
Setting n_values of OneHotEncoder for multiple columns?

### ISSUE THREAD

**Issue by bifeng** [scikit-learn-contrib/sklearn-pandas#148]
## For each columns has different unqiue values, then how to setting the n_values for each columns?
`from sklearn_pandas import gen_features

feature_def = gen_features(
     columns=[['col1'], ['col2'], ['col3']],
     classes=[{'class': sklearn.preprocessing.OneHotEncoder, 'n_values': ?}]
 )

mapper5 = DataFrameMapper(feature_def)

data5 = pd.DataFrame({
     'col1': [3, 2, 2],
     'col2': [2, 1, 2],
     'col3': [0, 0, 1]
 })

mapper5.fit_transform(data5)`

**Comment by dukebody** [comment]
Don't use the `gen_features`, Write the features explicitly:

```
features
```
