### ISSUE TITLE
DataFrameMapper cannot leverage special fit_transform methods

### ISSUE THREAD

**Issue by SandroCasagrande** [scikit-learn-contrib/sklearn-pandas#150]
For transformers in a DataFrameMapper, it would be useful to be able to access native combined fit_transform methods. This would allow e.g. for the different semantics of PCA(..., copy=False).fit_transform(X) versus .fit(X).transform(X), or the optimized version of DictVectorizer.fit_transform for sparse matrices, etc.

The current implementation of DataFrameMapper can only access each transformers fit and transform method successively. It's implementaion of fit_transform is the default inherited from TransformerMixin which always calls fit(...).transform(...).  

It should be quite simple to extend DataFrameMapper to account for this issue. I have the code prepared and will create a PR.

**Comment by FlorisHoogenboom** [comment]
It would be great to have this feature! There are many cases in which `fit_transform` should behave differently from `fit().transform()`, for examply when encoding categorical levels by leave-one-out means. Are there any plans to merge #152?

**Comment by dukebody** [comment]
Fixed in #169, which superseded #152 . Thanks!
