### ISSUE TITLE
Bug in DataFrameMapper.get_names: unicode feature names

### ISSUE THREAD

**Issue by AssafBenDavid** [scikit-learn-contrib/sklearn-pandas#160]
Hi,

When the features returned by a transformer (by `_get_feature_names`) are unicode strings containing non-ascii characters, `get_names` throws a `UnicodeEncodeError`. This is due to line 256 in `data frame_mapper.py`:
`return [name + '_' + str(o) for o in names]`
This assumes any object in `names` can be converted to string using `str`.
It would be much better to use something like `'%s_%s' % (name, o)`, which returns a unicode when needed. At the end, these strings become DataFrame column names, and DataFrames don't care about unicode indices.

**Comment by dukebody** [comment]
Thank you very much for the report and the contribution! Fixed in #165.
