### ISSUE TITLE
CategoricalImputer constant strategy

### ISSUE THREAD

**Issue by bjherger** [scikit-learn-contrib/sklearn-pandas#161]
- Update `CategoricalImputer` terminology to be consistent with [SimpleInputer](http://scikit-learn.org/dev/modules/generated/sklearn.impute.SimpleImputer.html#sklearn.impute.SimpleImputer)
   - fixed_value to constant
   - mode to most_frequent
   - replacement to fill_value
 - Update documentation to reference `strategy='constant'` strategy
 - Update default `fill_value` to `'?'`, consistent with `SimpleInputer`
 - Update unittests to match above
 - Unit test for default fill value

This could be a quick fix to refactoring the existing `strategy='fixed_value'` option, and updating documentation.

**Comment by dukebody** [comment]
Hi @bjherger ! Sounds nice and easy to implement? Would you be willing to do so? We can provide help with tests & code review.

**Comment by bjherger** [comment]
@dukebody Sounds perfect! I've begun reviewing the `contributing.md` document, and I'll get working on a first pass. 

Please feel free to assign this task to me, if you guys do that for tracking.

**Comment by bjherger** [comment]
@dukebody I've followed the contributing guide, written the code, and submitted a PR (#168 ). What's the best way to get feedback on this PR?

**Comment by devforfu** [comment]
@bjherger I'll review the changes today if I can do it before others.

**Comment by bjherger** [comment]
Adding unittest to acceptance criteria

**Comment by devforfu** [comment]
Solved with #168.
