### ISSUE TITLE
transform() is not threadsafe

### ISSUE THREAD

**Issue by tatome** [scikit-learn-contrib/sklearn-pandas#183]
https://github.com/scikit-learn-contrib/sklearn-pandas/blob/0024cf70d35bed7b0c0327c611210228ab5f11b4/sklearn_pandas/dataframe_mapper.py#L291

The property `DataFrameMapper.transformed_names_` is reassigned and modified during `_transform()`.  That makes `transform()` not thread safe and a Pipeline using a DataFrameMapper cannot be safely used in multiple threads.

**Comment by FlorisHoogenboom** [comment]
I guess this can be quite easily resolved by changing https://github.com/scikit-learn-contrib/sklearn-pandas/blob/0024cf70d35bed7b0c0327c611210228ab5f11b4/sklearn_pandas/dataframe_mapper.py#L310-L311
to something like 
```python
self.transformed_names_.extend(
    self.get_names(columns, transformers, Xt, alias) 
)
```
Or am I mistaken that `extend` is threadsafe?

**Comment by FlorisHoogenboom** [comment]
I'm sorry, I think I misunderstood the issue initially. I've prepared a PR that should resolve the actual issue.

**Comment by ragrawal** [comment]
Hi @FlorisHoogenboom 
Thanks for raising this issue. I took over the maintenance of sklearn-pandas and going through all the old issues. I think this is an important issue and should be fixed. I see your PR and happy to merge it. Wondering is there any way we can test this.

**Comment by FlorisHoogenboom** [comment]
In general it is very hard to test these kind of concurency safety models. I think the MR proposed at least fixxes some very obvious problems by making those operations more atomic. I wouldn't know any way to validate (except by deducing it from the operations performed) programmatically that this method is indeed thread safe now.

**Comment by ragrawal** [comment]
okie. I will review the MR and merge it. Thanks for your submission.
