### ISSUE TITLE
installing sklearn-pandas with anaconda on Mac

### ISSUE THREAD

**Issue by tsarav23** [scikit-learn-contrib/sklearn-pandas#186]

**Comment by tsarav23** [comment]
Request someone to help installing sklearn-pandas for my MacBook Air. Unable to get the package.

**Comment by FlorisHoogenboom** [comment]
You can use pip provided in your anaconda environment. Just activate the environment in which you wish to install sklearn-pandas and then call `pip install sklearn-pandas` as described in the readme.

**Comment by cguptac** [comment]
If you manage your conda environment with an `environment.yml` file, you can add the following lines to it:

```
- pip
- pip:
    - sklearn-pandas
```
