### ISSUE TITLE
How to avoid extra formating in get_names method of DataFrameMapper?

### ISSUE THREAD

**Issue by repko-artem** [scikit-learn-contrib/sklearn-pandas#187]
Hello. I have a question about implementation of the DataFrameMapper's method get_names.  When transformer implements its own get_feature_names method DataFrameMapper takes its result and then for some reason formats it
`return ['%s_%s' % (name, o) for o in names]`

My example. I have a list of date columns and transformer that creates 3 features from each column: day of month, week day and hour and returns matrix N x 3 (where N - date columns count). At method get_names this transformer generates a correct list of output features like 
`['DateCol1#Hour', 'DateCol1#WeekDay', 'DateCol1#DayOfMonth', "DateCol2#Hour', 'DateCol2#WeekDay', 'DateCol2#DayOfMonth']`.

But unfortunately DataFrameMapper "helps" me and concatenates this list with all input column names, so I get from mapper.transformed_names_ the list like 
`['DateCol1_DateCol2_DateCol1#Hour', 'DateCol1_DateCol2_DateCol1#WeekDay', 'DateCol1_DateCol2_DateCol1#DayOfMonth', "DateCol1_DateCol2_DateCol2#Hour', 'DateCol1_DateCol2_DateCol2#WeekDay', 'DateCol1_DateCol2_DateCol2#DayOfMonth']`

As you understand it's the simple case when I have an input with only 2 date columns, if there're more - its absolute hell. The worst is that I can't refuse in any way this "help". Maybe I use it in a wrong way? How to return the feature names I want?

**Comment by devforfu** [comment]
@repko-artem I think the only way to suppress this additional help is to use `alias=''` [parameter](https://github.com/scikit-learn-contrib/sklearn-pandas/blob/b6f6794f7bdfd7a7940c8edc1fec48ac26128b3a/sklearn_pandas/dataframe_mapper.py#L239) so the names will be shorter, and then apply additional filtering to drop trailing `_` character. 

Fill free to submit a PR so we can develop a better approach to generate column names, or at least suppress the unneeded help.

**Comment by jackwellsxyz** [comment]
Hi I'd +1 this feature request. I've got a handful of boolean features that I pass in a list to sklearn-pandas, and I get something like `feature0_feature1_feature2_feature3_feature4_0` to mean `feature0`. It gets a little more confusing when I have feature names that already have underscores in them; in this case, it's not so easy to tell which feature the `0` is referring to. Is anyone already working on this by chance? cc: @repko-artem.

**Comment by repko-artem** [comment]
In our project we fixed it in this way:
```
from sklearn_pandas import DataFrameMapper
from sklearn_pandas import pipeline
# noinspection PyProtectedMember
from sklearn_pandas.dataframe_mapper import _get_feature_names


class DataFrameMapperFix(DataFrameMapper):
	"""
	Temporary fix for transformed names.
	Method get_names() avoids adding prefix made of concatenated feature names.
	The rest of the implementation is identical.

	GitHub issue:
	https://github.com/scikit-learn-contrib/sklearn-pandas/issues/187

	TODO: Remove when it is closed.
	"""

	def get_names(self, columns, transformer, x, alias = None):
		"""
		Return verbose names for the transformed columns.

		columns       name (or list of names) of the original column(s)
		transformer   transformer - can be a TransformerPipeline
		x             transformed columns (numpy.ndarray)
		alias         base name to use for the selected columns
		"""
		if alias is not None:
			name = alias
		elif isinstance(columns, list):
			name = '_'.join(map(str, columns))
		else:
			name = columns
		num_cols = x.shape[1] if len(x.shape) > 1 else 1
		if num_cols >= 1:
			if isinstance(transformer,  pipeline.TransformerPipeline):
				inverse_steps = transformer.steps[::-1]
				estimators = (estimator for name, estimator in inverse_steps)
				names_steps = (_get_feature_names(e) for e in estimators)
				names = next((n for n in names_steps if n is not None), None)
			else:
				names = _get_feature_names(transformer)
			if names is not None and len(names) == num_cols:
				# Original code:
				# return ['%s_%s' % (name, o) for o in names]
				if alias is not None:                            # Temporary fix is here.
					return ['%s%s' % (alias, o) for o in names]  # Prepend name prefix only if alias
				return names                                     # is explicitly specified.
			else:
				return [name + '_' + str(o) for o in range(num_cols)]
		else:                                                    # Fix: Should return empty array if
			return []                                            # transformed matrix has no columns
```

**Comment by ragrawal** [comment]
Along with `alias` you can know also provide `prefix` and `postfix`

```
>>> mapper_alias = DataFrameMapper([
...     (['children'], sklearn.preprocessing.StandardScaler(), {'prefix': 'standard_scaled_'}),
...     (['children'], sklearn.preprocessing.StandardScaler(), {'suffix': '_raw'})
... ])
>>> _ = mapper_alias.fit_transform(data.copy())
>>> mapper_alias.transformed_names_
['standard_scaled_children', 'children_raw']
```
