### ISSUE TITLE
Provide tags for releases in source code

### ISSUE THREAD

**Issue by inglor** [scikit-learn-contrib/sklearn-pandas#191]
Hi,

As a [maintainer] of the package in Archlinux I'd like to request to consider providing tags for the releases. A tag can prove useful to reproducible builds and points exactly in source history when the release was done. It's a much better representation of an arbitrary artifact packaged and uploaded in PyPI.

Thanks,
Leonidas

[maintainer]: https://aur.archlinux.org/packages/python-sklearn-pandas/

**Comment by devforfu** [comment]
@inglor Hi! Makes sense. I guess we have a few but for quite old versions only.

**Comment by ragrawal** [comment]
I started doing this again. Looking for a way to automate this using github actions. Let me know if you have any idea/suggestions.

**Comment by inglor** [comment]
Hi @ragrawal it depends on your approach for releases.

If you want a flourish of releases you can make github action tag the master branch on every PR merge. Then provided you are only allowing commits to master/main branch only from merges (i.e. from a PR) then you have a new release on every merge.

If your model for releases is different then maybe you can push a specific commit message or an annotated tag to trigger a "release".

How do you think this would work? Can you lock the master/main branch and enforce everyone who develop to work with PRs?
