### ISSUE TITLE
Calling transform on a non-fitted DataFrameMapper raises TypeError

### ISSUE THREAD

**Issue by FlorisHoogenboom** [scikit-learn-contrib/sklearn-pandas#192]
When calling transform on a `DataFrameMapper` that hasn't been fitted yet, the `TypeError` below is raised:

```
TypeError: 'NoneType' object is not iterable
```

It would be nice to have a more meaningful error since this is hard to debug. Ideally, we would check whether we are able to call transform on all underlying transformers and only raise of one of these is not successful. This may be difficult to implement since there is generic way that I know of to determine whether a Scikit-learn transformer is fitted. 

Anyways, I would be happy to submit a PR for a more meaningful error message!

**Comment by ragrawal** [comment]
@FlorisHoogenboom I recently took over maintenance of this library. If you have PR for this, I can take a look and merge it.
