### ISSUE TITLE
Are SKLEARN API estimators can distinguish PANDAS nominal type feature and PANDAS ordinal type feature?

### ISSUE THREAD

**Issue by muketer** [scikit-learn-contrib/sklearn-pandas#195]
Are SKLEARN API estimators, e.z. XGBOOSTRegressor and LGBMRegressor and CatBoostRegressor,
can recognize difference between
'ordinal feature (applying pandas.api.types.CategoricalDtype(data, ordered=True))'
and
'nominal feature (applying pandas.api.types.CategoricalDtype(data, ordered=False))' ?

thank you for your help.

**Comment by ragrawal** [comment]
you might want to post this question on sklearn forum
