### ISSUE TITLE
Question about Transforming Multiple Columns

### ISSUE THREAD

**Issue by sskarkhanis** [scikit-learn-contrib/sklearn-pandas#199]
Hello 

I just discovered sklearn_pandas and really like it.
I was trying to transform multiple columns as shown in the examples but can't get it to work.

I would really appreciate if you could please tell me what I'm doing wrong?
I tried replicating this with the dummy data frame you use in the example but it gives the same error.
Thanks!

##### Code

import pandas as pd
from sklearn_pandas import *
from sklearn.pipeline import Pipeline 
from sklearn.cluster import KMeans

data = pd.DataFrame({'pet':      ['cat', 'dog', 'dog', 'fish', 'cat', 'dog', 'cat', 'fish'],
                     'children': [4., 6, 3, 3, 2, 3, 5, 4],
                      'salary':   [90., 24, 44, 27, 32, 59, 36, 27]})

mapper2 = DataFrameMapper([
          (['children', 'salary'], KMeans(n_clusters=2,verbose=1))
      ])

##### Method 1
np.round(mapper2.fit_transform(data[['children', 'salary']].copy()))

mapper2.predict(data[['children', 'salary']].copy())
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-65-e168bf2c2584> in <module>
----> 1 mapper2.predict(data[['children', 'salary']].copy())

AttributeError: 'DataFrameMapper' object has no attribute 'predict'

##### Method 2
p = Pipeline([('apply clustering', mapper2)],verbose=True)

np.round(p.fit_transform(data[['children', 'salary']].copy()))
[Pipeline] .. (step 1 of 1) Processing apply clustering, total=   0.0s

p.predict(data[['children', 'salary']].copy())
AttributeError: 'DataFrameMapper' object has no attribute 'predict'

**Comment by paro1234** [comment]
Method 1 no longer gives Attribute error. Here is the output. 
`   pet  children  salary
0   cat       4.0    90.0
1   dog       6.0    24.0
2   dog       3.0    44.0
3  fish       3.0    27.0
4   cat       2.0    32.0
5   dog       3.0    59.0
6   cat       5.0    36.0
7  fish       4.0    27.0
Initialization complete
Iteration 0, inertia 1035.0
Iteration 1, inertia 925.1428571428571
Converged at iteration 1: strict convergence.
Initialization complete
Iteration 0, inertia 1035.0
Iteration 1, inertia 925.1428571428571
Converged at iteration 1: strict convergence.
Initialization complete
Iteration 0, inertia 2163.0
Iteration 1, inertia 765.1666666666666
Converged at iteration 1: strict convergence.
Initialization complete
Iteration 0, inertia 1426.0
Iteration 1, inertia 925.1428571428571
Converged at iteration 1: strict convergence.
Initialization complete
Iteration 0, inertia 938.0
Iteration 1, inertia 925.1428571428571
Converged at iteration 1: strict convergence.
Initialization complete
Iteration 0, inertia 1381.0
Iteration 1, inertia 765.1666666666666
Converged at iteration 1: strict convergence.
Initialization complete
Iteration 0, inertia 1381.0
Iteration 1, inertia 765.1666666666666
Converged at iteration 1: strict convergence.
Initialization complete
Iteration 0, inertia 1443.0
Iteration 1, inertia 1008.617777777778
Iteration 2, inertia 765.1666666666666
Converged at iteration 2: strict convergence.
Initialization complete
Iteration 0, inertia 938.0
Iteration 1, inertia 925.1428571428571
Converged at iteration 1: strict convergence.
Initialization complete
Iteration 0, inertia 1312.0
Iteration 1, inertia 1008.617777777778
Iteration 2, inertia 765.1666666666666
Converged at iteration 2: strict convergence.`

**Comment by paro1234** [comment]
The object mapper2 in this case support 'fit', 'transform' and 'fit_transform' functionality only. 'Predict' will not work.
