### ISSUE TITLE
I can't find a way to transform multiple features but with different transforms

### ISSUE THREAD

**Issue by DemirTonchev** [scikit-learn-contrib/sklearn-pandas#200]
Is it possible to apply transformation just to one variable and then proceed to transform all of the selected like so?
`
mapper = DataFrameMapper([
('pet', sklearn.preprocessing.LabelBinarizer()),
(['children','salary'], [{'salaly':FunctionTransformer(np.log)}, PCA(),])
])
`
I want to apply some function to 'salary' but then proceed to PCA for both of the variables.

**Comment by ragrawal** [comment]
@DemirTonchev you can use gen_features to generate transformations for all other columns. Something like this

```
mapper = DataFrameMapper(
 gen_features(
  columns = df.columns,
  classes = [PCA]
 ) + 
[
  ('pet', LabelBinarizer()),
  (['children', 'salary'], PCA())
]
)
```
