### ISSUE TITLE
how to deal with MultiLabelBinarizer

### ISSUE THREAD

**Issue by zjcanjux** [scikit-learn-contrib/sklearn-pandas#202]
from sklearn.preprocessing import OneHotEncoder,LabelEncoder,MultiLabelBinarizer
from sklearn_pandas import DataFrameMapper

X = pd.DataFrame({'city': ['tokyo', 'london', 'london', 'seattle', 'san francisco', 'tokyo'],
                  'multilabel':[['a1','a2'],['a1'],['a3'],['a4'],['a5'],['a6']],
                  })

mapper = DataFrameMapper([
    (['multilabel'],MultiLabelBinarizer())
])
pipeline = Pipeline([
  ("mapper", mapper),
])
print(pipeline.fit_transform(X.copy()))
arise: ['multilabel']: unhashable type: 'list'

when I convert it to 

X = pd.DataFrame({'city': ['tokyo', 'london', 'london', 'seattle', 'san francisco', 'tokyo'],
                  'multilabel':["['a1','a2']","['a1']","['a3']","['a4']","['a5']","['a6']"],
                  })
output:
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]

is not multilabel.

so how to deal with multilabelencoder?

**Comment by ragrawal** [comment]
MultilabelBinarizer expects a single column as an input. You need to replace mapper with this 

```
mapper = DataFrameMapper([
('multilabel',MultiLabelBinarizer()).  # note replacing ['multilabel'] with 'multilabel'
])
```
