### ISSUE TITLE
[Question] Want to contribute. looking for good first issue

### ISSUE THREAD

**Issue by paro1234** [scikit-learn-contrib/sklearn-pandas#203]
Hi, 
I want to contribute to this awesome library. Can you point me to any good first issue? All I checed were either done or PR pending. 
Thanks a ton.

**Comment by ragrawal** [comment]
@paro1234 Thanks for your interest in contributing to this library. Here is one interesting and simple issue to look into: https://github.com/scikit-learn-contrib/sklearn-pandas/issues/208
