### ISSUE TITLE
OneHotEncoder returning 'x0' in column names

### ISSUE THREAD

**Issue by FelixChop** [scikit-learn-contrib/sklearn-pandas#204]
Probably something that was seen before, but it makes it tricky to use the DataFrameMapper in a production-ready pipeline, since one needs to add a `.rename()` with multiple column names. 

Example seen below:
`from sklearn.preprocessing import OneHotEncoder`
`onehotencoder = OneHotEncoder()`

`df = pd.DataFrame({`
`    'categorical': ['A', 'B', 'C']`
`})`

`mapper = DataFrameMapper([`
`    (['categorical'], onehotencoder)`
`], df_out=True)`

`mapper.fit_transform(df)`

returns
`categorical_x0_A	categorical_x0_B	categorical_x0_C`
`0	1.0	0.0	0.0`
`1	0.0	1.0	0.0`
`2	0.0	0.0	1.0`

**Comment by ragrawal** [comment]
@FelixChop Yup I noticed the same issue and it's because of some recent changes in sklearn library itself. The classes_ variable returned by sklearn includes x0, x1 as they support multiple columns.
