### ISSUE TITLE
DataFrameMapper x SimpleImputer outputs an error with a DataFrame with 1 row

### ISSUE THREAD

**Issue by FelixChop** [scikit-learn-contrib/sklearn-pandas#205]
I am trying to run the DataFrameMapper for a DataFrame with 1 row in order to do some what-if analysis with my data prep pipeline. 1 row doesn't seem to work. More than 1 row can work if you add non missing values. Examples below:

`import pandas as pd`
`from sklearn_pandas import DataFrameMapper`
`from sklearn.impute import SimpleImputer`

`df = pd.DataFrame({`
`    'column_1': ['A', 'B', np.nan]`
`})`

`imputer = SimpleImputer(strategy='constant', fill_value='A')`

`mapper = DataFrameMapper([`
`    (['column_1'], imputer)`
`])`

`mapper.fit(df)`

Here you'll get an error:

`mapper.transform(pd.DataFrame({`
`    'column_1': [np.nan]`
`}))`

Here you'll get the expected outcome:
`mapper.transform(pd.DataFrame({`
`    'column_1': [np.nan, 'A']`
`}))`

**Comment by FelixChop** [comment]
Note that it returns an error only if SimpleImputer is used for categorical variables. For numeric variables, no problem:

`df = pd.DataFrame({`
`    'column_1': [1, 2, np.nan]`
`})`

`imputer = SimpleImputer(strategy='constant', fill_value='A')`

`mapper = DataFrameMapper([`
`   (['column_1'], imputer)`
`])`

`mapper.fit(df)`

This works:

`mapper.transform(pd.DataFrame({`
`   'column_1': [np.nan]`
`}))`

**Comment by ragrawal** [comment]
@FelixChop I am not able to replicate your issue. Can you try the latest version sklearn and let me know if you still see the issue. Closing it out for now but feel free to reopen if the issue persists.
