### ISSUE TITLE
Unable to apply StandardScaler to multiple columns

### ISSUE THREAD

**Issue by dpatschke** [scikit-learn-contrib/sklearn-pandas#214]
The following code snippet is returning an error for me. I'm not sure whether there are some scikit-learn transformers that are now requiring a 2d array rather than 1d but the error I am receiving from scikit-learn is that a 2d array is being required for StandardScaler. I forked the code and tried to correct myself in `_get_col_subset` but to no avail.

I'm using sklearn-pandas 2.0.0

```
from sklearn.preprocessing import StandardScaler
import pandas as pd

from sklearn_pandas import DataFrameMapper
from sklearn_pandas import gen_features

foo = pd.DataFrame({'col1': [1,2,3,4],
                    'col2': [5,6,7,8],
                    'col3': [9,10,11,12]})

feature_def = gen_features(
    columns=foo.columns,
    classes=[StandardScaler],
    suffix="_zscore")

mapper = DataFrameMapper(feature_def, df_out=True)

data_transformed = mapper.fit_transform(foo)
```

**Comment by dpatschke** [comment]
Ok ... did a bit more probing on this.

It appears the only scikit-learn preprocessing transformer that actually works with a 1d array vs. 2d array is the one that iss shown as an example in the README for `gen_features` ... LabelEncoder. All others appear to either require or support a 2d-array.

I was able to fix the problem by changing the line on 195 in dataframe_mapper.py to the following:
```
return t.values.reshape(-1,1)
```

I tested the `gen_features` SimpleImputer example on the README as well with fix above and it works.

**Comment by ragrawal** [comment]
@dpatschke thanks for reporting this. Another option is to explicit provide an array of columns. This should work . 

```
from sklearn.preprocessing import StandardScaler
import pandas as pd

from sklearn_pandas import DataFrameMapper
from sklearn_pandas import gen_features

foo = pd.DataFrame({'col1': [1,2,3,4],
                    'col2': [5,6,7,8],
                    'col3': [9,10,11,12]})

feature_def = gen_features(
    columns=list(map(lambda x: [x], foo.columns)) ,
    classes=[StandardScaler],
    suffix="_zscore")

mapper = DataFrameMapper(feature_def, df_out=True)

data_transformed = mapper.fit_transform(foo)
print(data_transformed)
```

**Comment by dpatschke** [comment]
@ragrawal Thanks for the workaround! I did notice the wrapping of column names in a list in one of the examples but failed to make the connection presented in your suggestion. Thanks again!
