### ISSUE TITLE
drop_cols= ... doesn't exist

### ISSUE THREAD

**Issue by alxfed** [scikit-learn-contrib/sklearn-pandas#218]
Regarding your claim:

https://github.com/scikit-learn-contrib/sklearn-pandas#dropping-columns-explictly

TypeError: __init__() got an unexpected keyword argument 'drop_cols'

**Comment by ragrawal** [comment]
which version of sklearn-pandas are you using? Please make sure to upgrade it to 2.0.1

**Comment by alxfed** [comment]
Ha-ha-ha!
