### ISSUE TITLE
add to conda-forge?

### ISSUE THREAD

**Issue by raybellwaves** [scikit-learn-contrib/sklearn-pandas#220]
Any interest to add this package to conda-forge? I tend to use that as my default package installer?

Fairly easy now with Grayskull: https://www.marcelotrevisani.com/grayskull

**Comment by ragrawal** [comment]
Hi @raybellwaves .. this is on my todo list. Let me checkout this Grayskull . Thanks for prompting this

**Comment by raybellwaves** [comment]
https://github.com/conda-forge/sklearn-pandas-feedstock
