### ISSUE TITLE
Can someone help me with this code? Maybe its a problem of the version. Thanks

### ISSUE THREAD

**Issue by ACassoni** [scikit-learn-contrib/sklearn-pandas#223]
`from sklearn_pandas import DataFrameMapper
from sklearn.preprocessing import StandardScaler, LabelEncoder
mapper_df = DataFrameMapper([
    (["age"], None),
    ("workclass", LabelEncoder()),
    ("maxEdu", LabelEncoder()),
    ("civilStatus", LabelEncoder()),
    ("workType", LabelEncoder()),
    ("relationship", LabelEncoder()),
    ("race", LabelEncoder()),
    (["hrs-week"], StandardScaler()),
    (["Target"], None),
    (["Gender"], None), 
    (["Origin"], None)
], df_out = True)

mapper_fit = mapper.fit(df)
train_processed = mapper.transform(df)

    
train_processed.head()`

It gives me the following error: 
TypeError                                 Traceback (most recent call last)
<ipython-input-39-0221f21f5a84> in <module>
     17 
     18 
---> 19 mapper_fit = mapper.fit(df)
     20 train_processed = mapper.transform(df)
     21 

c:\users\usuario\python\lib\site-packages\sklearn_pandas\dataframe_mapper.py in fit(self, X, y)
    221             if transformers is not None:
    222                 with add_column_names_to_exception(columns):
--> 223                     Xt = self._get_col_subset(X, columns, input_df)
    224                     _call_fit(transformers.fit, Xt, y)
    225             logger.info(f"[FIT] {columns}: {_elapsed_secs(t1)} secs")

c:\users\usuario\python\lib\site-packages\sklearn_pandas\dataframe_mapper.py in _get_col_subset(self, X, cols, input_df)
    187         # Will be dropped on sklearn-pandas 2.0.
    188         if isinstance(X, list):
--> 189             X = [x[cols] for x in X]
    190             X = pd.DataFrame(X)
    191 

c:\users\usuario\python\lib\site-packages\sklearn_pandas\dataframe_mapper.py in <listcomp>(.0)
    187         # Will be dropped on sklearn-pandas 2.0.
    188         if isinstance(X, list):
--> 189             X = [x[cols] for x in X]
    190             X = pd.DataFrame(X)
    191 

TypeError: ['workclass']: tuple indices must be integers or slices, not list

**Comment by ragrawal** [comment]
I think labelEncoder expects an array. Try this 
`(['workclass'], LabelEncoder()),`

**Comment by ACassoni** [comment]
It worked, thank you!
