### ISSUE TITLE
can you share why it is better than to use only pandas is it faster or less code?

### ISSUE THREAD

**Issue by Sandy4321** [scikit-learn-contrib/sklearn-pandas#234]
can you share why it is better than to use only pandas
is it faster or less code?

**Comment by ragrawal** [comment]
Can you provide me context by what do you mean "better than to use only pandas". Are asking about sklearn-pandas and what it provides ? If so, sklearn-pandas is not about speed but more about convenience and less code. One of the biggest advantages that it provides lineage information about how features were constructed. Apart from that, it's a lot more succient than trying to use plain vanilla sklearn and pandas libraries. Another factor is the readability. It's much easier to read a single array block than 100 lines of code.
