### ISSUE TITLE
the name of cross multiplicative term is not i want

### ISSUE THREAD

**Issue by weidongzhou1994** [scikit-learn-contrib/sklearn-pandas#243]
as title

when I use the PolynomialFeatures to generate the cross multiplicative term, the name is confusion.

![image](https://user-images.githubusercontent.com/40510496/110080262-2d7b0b80-7dc5-11eb-8157-c68d2c619867.png)

**Comment by ragrawal** [comment]
Hi @weidongzhou1994 
You can use alias term . 
mapper = DataFrameMapper([
   (['out', 'inner'], [sklearn...], {'alias': 'xyz'})
], ...)

Then the name of the fields will be 'xyz_x0', 'xyz_x1', , ..
