### ISSUE TITLE
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

### ISSUE THREAD

**Issue by Kaushal-Prasad** [scikit-learn-contrib/sklearn-pandas#247]
lr1 = LogisticRegression(C=4,penalty='l1', verbose=5)
lr1.fit(X_train_res, y_train_res.ravel())

ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

I'm getting the below error. Can anyone help check?

**Comment by devforfu** [comment]
@Kaushal-Prasad as the error reads, the `lbfgs` solver (the default choice for the `LogisticRegression`) doesn't support this kind of penalty. Try to pick another solver, like:
```python
reg = LogisticRegression(solver="saga", penalty="l1")
```
As this repo is for `sklearn-pandas` interface, please refer to the [`scikit-learn`s documentation](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html) to get more information.
